"""Regenerate the deterministic traffic baseline in edges_clean.js.

Each edge keeps its topology (source, target, distance, base time, road type)
but gets a new per-edge congestion level (1-5) and risk factor (1.0-5.0).

The randomization uses a fixed seed so the regenerated baseline is
reproducible across runs (important for Lab evaluation). Road types keep
realistic tendencies: main streets are more congested, access roads carry
higher risk, and one-way streets are generally free-flowing.

Usage:
    python -m scripts.randomize_traffic_baseline [--seed 42]
"""

from __future__ import annotations

import argparse
import json
import random
from collections import Counter
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parents[1] / "data"
EDGES_FILE = DATA_DIR / "edges_clean.js"

DEFAULT_SEED = 42

# Weighted congestion distributions by road type (sums to 1.0).
CONGESTION_WEIGHTS = {
    "main_street": {1: 0.05, 2: 0.15, 3: 0.35, 4: 0.30, 5: 0.15},
    "one_way": {1: 0.10, 2: 0.40, 3: 0.33, 4: 0.14, 5: 0.03},
    "access": {1: 0.05, 2: 0.40, 3: 0.38, 4: 0.14, 5: 0.03},
}

# Risk factor ranges by road type.
RISK_RANGES = {
    "main_street": (2.0, 4.5),
    "one_way": (1.0, 3.0),
    "access": (1.5, 3.8),
}


def fmt_number(value: float, max_decimals: int) -> str:
    """Format a float trimming trailing zeros but keeping a decimal point."""
    text = f"{value:.{max_decimals}f}".rstrip("0").rstrip(".")
    if text in {"", "-"}:
        return "0.0"
    return text if "." in text else text + ".0"


def parse_edges(text: str) -> tuple[list[dict], str]:
    """Return the edge objects plus the leading comment header."""
    start = text.index("const EDGES_CLEAN = [")
    array_start = text.index("[", start)
    array_end = text.rindex("]")
    header = text[: start].rstrip()
    edges = json.loads(text[array_start : array_end + 1])
    return edges, header


def serialize_edges(edges: list[dict]) -> str:
    """Serialize edges back to the exact JS object format used upstream."""
    lines = ["const EDGES_CLEAN = ["]
    for index, edge in enumerate(edges):
        lines.append("  {")
        lines.append(f'    "source": {edge["source"]},')
        lines.append(f'    "target": {edge["target"]},')
        lines.append(
            f'    "distance_km": {fmt_number(float(edge["distance_km"]), 3)},'
        )
        lines.append(
            f'    "base_time_min": {fmt_number(float(edge["base_time_min"]), 2)},'
        )
        lines.append(f'    "congestion_level": {int(edge["congestion_level"])},')
        lines.append(f'    "road_type": "{edge["road_type"]}",')
        lines.append(f'    "risk_factor": {fmt_number(float(edge["risk_factor"]), 2)}')
        lines.append("  }," if index < len(edges) - 1 else "  }")
    lines.append("];")
    return "\n".join(lines)


def randomize_edge(edge: dict, rng: random.Random) -> None:
    """Assign a realistic random congestion level and risk factor in place."""
    road_type = edge["road_type"]
    weights = CONGESTION_WEIGHTS.get(road_type, CONGESTION_WEIGHTS["one_way"])
    edge["congestion_level"] = rng.choices(
        population=sorted(weights),
        weights=[weights[level] for level in sorted(weights)],
        k=1,
    )[0]

    low, high = RISK_RANGES.get(road_type, RISK_RANGES["one_way"])
    edge["risk_factor"] = round(rng.uniform(low, high), 2)


def new_header() -> str:
    return (
        "// edges_clean.js - Clean directed traffic graph edges.\n"
        "// Sources: OSM via Build_Dataset.py and food_places.json via build_food.py.\n"
        "// Total: 176 edges using one_way, main_street, and access road types.\n"
        "// Traffic fields use a deterministic randomized baseline (fixed seed) with\n"
        "// realistic per-edge congestion (1-5) and risk (1.0-5.0) for Lab evaluation.\n"
        "// Regenerated by randomize_traffic_baseline.py; do not edit manually."
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    args = parser.parse_args()

    original = EDGES_FILE.read_text(encoding="utf-8")
    edges, _header = parse_edges(original)
    total_before = len(edges)

    rng = random.Random(args.seed)
    for edge in edges:
        randomize_edge(edge, rng)

    congestion_counts = Counter(edge["congestion_level"] for edge in edges)
    risk_values = {edge["risk_factor"] for edge in edges}
    distribution = Counter(
        (edge["road_type"], edge["congestion_level"]) for edge in edges
    )

    if len(congestion_counts) < 3 or len(risk_values) < 3:
        raise SystemExit(
            "Randomized baseline violates the >= 3 distinct values test constraint."
        )

    output = new_header() + "\n" + serialize_edges(edges) + "\n"
    EDGES_FILE.write_text(output, encoding="utf-8")

    print(f"Regenerated {total_before} edges with seed={args.seed}.")
    print(f"Congestion distribution: {dict(sorted(congestion_counts.items()))}")
    print(
        "By road type (road_type: {level: count}): "
        + json.dumps(
            {
                road: {
                    level: distribution[(road, level)]
                    for level in sorted(CONGESTION_WEIGHTS[road])
                    if distribution[(road, level)]
                }
                for road in sorted(CONGESTION_WEIGHTS)
            }
        )
    )
    print(
        f"Distinct risk factors: {len(risk_values)} (range "
        f"{min(risk_values):.2f}-{max(risk_values):.2f})."
    )


if __name__ == "__main__":
    main()
